### ISSUE TITLE
In diagonalize_ladder, what do indices where qubit level is higher than total excitation mean?

### ISSUE THREAD

**Issue by zchen088** [MostafaKhezri/JC-ladder#4]
For example, what does the value in `eigen_energies[0, 5]` mean?

**Comment by MostafaKhezri** [comment]
Short answer: for `eigen_energies[n, q]` where `q>n`, the eigenenergy is a non-physical value of `(n-q)*omega_r + qubit_energy_list[q]` an should be discared.

Long answer: At the bottom of the JC ladder, number of total states in a RWA strip is smaller than total transmon levels and it reaches this value only at total excitation number of `len(qubit_energy_list)` and then remains fixed thereafter. Therefore at the bottom of the ladder in order to avoid constructing arrays with different sizes, I still construct the RWA strip with `(tot_excit-q)*omega_r + qubit_energy_list[q]`, but I turn the coupling to these non-physical levels off ([see here](https://github.com/MostafaKhezri/JC-ladder/blob/352d7377745e84f7c51985a9d3cc3cebccde7edb/JC.py#L55)) so that they do not change the eigenenergy calculations.

**Comment by MostafaKhezri** [comment]
Closing this issue. Please reopen if still unclear.
